# Generated by Django 4.2.4 on 2023-08-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('member_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField(default='NA', max_length=100)),
                ('books_issued', models.JSONField(default={})),
                ('due', models.FloatField(default=0.0)),
                ('issued_books_number', models.IntegerField(default=0)),
            ],
        ),
    ]
