# Generated by Django 4.2.4 on 2023-08-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='contact',
            field=models.TextField(default='NA', max_length=10),
        ),
    ]
