# Generated by Django 4.2.4 on 2023-08-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='member_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
