# Generated by Django 4.2.4 on 2023-08-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_members_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='books_issued',
            field=models.JSONField(default={'books': []}),
        ),
    ]
