# Generated by Django 4.2.4 on 2023-08-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('authors', models.TextField(max_length=100)),
                ('isbn', models.BigIntegerField()),
                ('publisher', models.TextField(max_length=100)),
                ('rating', models.FloatField()),
                ('stocks', models.IntegerField()),
            ],
        ),
    ]
