# Generated by Django 4.2.4 on 2023-08-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.TextField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.TextField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.TextField(default='NA', max_length=100),
        ),
    ]
