# Generated by Django 4.2.4 on 2023-08-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_authors_alter_books_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.TextField(default='NA'),
        ),
    ]
