# Generated by Django 4.2.4 on 2023-08-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='book_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='transactions',
            name='member_id',
            field=models.IntegerField(default=-1),
        ),
    ]
